import 'package:flutter/material.dart';

part 'bottom/company_create_botton.dart';
part 'bottom/create_product_bottom.dart';
part 'bottom/login_bottom.dart';
part 'bottom/registration_bottom.dart';
part 'bottom/statistic_bottom.dart';
part 'cards/company_info_card.dart';
part 'cards/managers_card.dart';
part 'cards/product_card.dart';
part 'cards/registration_сonfirm_mail_card.dart';
part 'input/bic_inputs.dart';
part 'input/checking_account_inputs.dart';
part 'input/correspondent_check_inputs.dart';
part 'input/email_inputs.dart';
part 'input/fio_inputs.dart';
part 'input/name_company_inputs.dart';
part 'input/password_input.dart';
part 'text/text_widget.dart';
